### ISSUE TITLE
Implement User Authentication

### ISSUE THREAD

**Issue by parththkkr** [parththkkr/Menu-Maker#6]
@Iramfatema 

**Develop functionality to allow users to create accounts and log in securely.**

Tasks:

- [x] Set up Django's built-in authentication system or use a third-party package like Django Allauth.
- [x] Create user registration view and template with form for user registration.
- [x] Implement login view and template with form for user authentication.
- [x] Integrate authentication with Django's User model or a custom user model.

**Comment by Iramfatema** [comment]
Implemented secure user registration and login functionality

- Set up Django's built-in authentication system for secure user management
- Created user registration view and template with a form for user registration
- Implemented login view and template with a form for user authentication
- Integrated authentication with Django's User model for robust user authentication

**Comment by parththkkr** [comment]
Reviewed and merged
