### ISSUE TITLE
Implement Cart Viewing Feature

### ISSUE THREAD

**Issue by parththkkr** [parththkkr/Menu-Maker#7]
@aakarshandutt011 

**Description: Enable users to view their current cart contents, including items added for purchase.**

Tasks:
- [x] Design cart view and template to display cart items and total price.
- [x] Implement view function to fetch cart data from session or database.
- [x] Render cart data dynamically in the template using Django templates and HTML.
- [x] Handle scenarios such as empty cart and display appropriate messages.

**Comment by aakarshandutt011** [comment]
implemented cart view functionality for displaying current cart contents

Designed cart view and template to display cart items and total price
Implemented view function to fetch cart data from session or database
Rendered cart data dynamically in the template using Django templates and HTML
Handled scenarios such as empty carts and displayed appropriate messages

**Comment by parththkkr** [comment]
Review and Merged.
